struct Colors {
    const char* aliceblue;
    const char* alizarin;
    const char* amethyst;
    const char* antiquewhite;
    const char* aqua;
    const char* aquamarine;
    const char* asbestos;
    const char* azure;
    const char* beige;
    const char* belizehole;
    const char* bisque;
    const char* black;
    const char* blanchedalmond;
    const char* blue;
    const char* blueviolet;
    const char* brown;
    const char* buff;
    const char* burlywood;
    const char* cadetblue;
    const char* carrot;
    const char* chartreuse;
    const char* chocolate;
    const char* clouds;
    const char* concrete;
    const char* coral;
    const char* cornflowerblue;
    const char* cornsilk;
    const char* crimson;
    const char* cyan;
    const char* darkblue;
    const char* darkbrown;
    const char* darkbuff;
    const char* darkcyan;
    const char* darkgold;
    const char* darkgoldenrod;
    const char* darkgray;
    const char* darkgreen;
    const char* darkgrey;
    const char* darkivory;
    const char* darkkhaki;
    const char* darkmagenta;
    const char* darkmustard;
    const char* darkolivegreen;
    const char* darkorange;
    const char* darkorchid;
    const char* darkpink;
    const char* darkred;
    const char* darksalmon;
    const char* darksilver;
    const char* darkseagreen;
    const char* darkslateblue;
    const char* darkslategray;
    const char* darkslategrey;
    const char* darkturquoise;
    const char* darkviolet;
    const char* darkyellow;
    const char* deeppink;
    const char* deepskyblue;
    const char* dimgray;
    const char* dimgrey;
    const char* dodgerblue;
    const char* emerald;
    const char* firebrick;
    const char* floralwhite;
    const char* forestgreen;
    const char* fuchsia;
    const char* gainsboro;
    const char* ghostwhite;
    const char* gold;
    const char* goldenrod;
    const char* gray;
    const char* green;
    const char* greensea;
    const char* greenyellow;
    const char* grey;
    const char* honeydew;
    const char* hotpink;
    const char* indianred;
    const char* indigo;
    const char* ivory;
    const char* khaki;
    const char* lavender;
    const char* lavenderblush;
    const char* lawngreen;
    const char* lemonchiffon;
    const char* lightblack;
    const char* lightblue;
    const char* lightbrown;
    const char* lightbuff;
    const char* lightcoral;
    const char* lightcyan;
    const char* lightgold;
    const char* lightgoldenrod;
    const char* lightgoldenrodyellow;
    const char* lightgray;
    const char* lightgreen;
    const char* lightgrey;
    const char* lightivory;
    const char* lightmagenta;
    const char* lightmustard;
    const char* lightorange;
    const char* lightpink;
    const char* lightred;
    const char* lightsalmon;
    const char* lightseagreen;
    const char* lightsilver;
    const char* lightskyblue;
    const char* lightslategray;
    const char* lightslategrey;
    const char* lightsteelblue;
    const char* lightturquoise;
    const char* lightviolet;
    const char* lightyellow;
    const char* lime;
    const char* limegreen;
    const char* linen;
    const char* magenta;
    const char* maroon;
    const char* mediumaquamarine;
    const char* mediumblue;
    const char* mediumorchid;
    const char* mediumpurple;
    const char* mediumseagreen;
    const char* mediumslateblue;
    const char* mediumspringgreen;
    const char* mediumturquoise;
    const char* mediumvioletred;
    const char* midnightblue;
    const char* midnightblack;
    const char* mintcream;
    const char* mistyrose;
    const char* moccasin;
    const char* mustard;
    const char* nephritis;
    const char* navajowhite;
    const char* navy;
    const char* oldlace;
    const char* olive;
    const char* olivedrab;
    const char* orange;
    const char* orangered;
    const char* orchid;
    const char* palegoldenrod;
    const char* palegreen;
    const char* paleturquoise;
    const char* palevioletred;
    const char* papayawhip;
    const char* peachpuff;
    const char* peterriver;
    const char* peru;
    const char* pink;
    const char* plum;
    const char* pomegranate;
    const char* powderblue;
    const char* purple;
    const char* pumpkin;
    const char* rebeccapurple;
    const char* red;
    const char* rosybrown;
    const char* royalblue;
    const char* saddlebrown;
    const char* salmon;
    const char* sandybrown;
    const char* seagreen;
    const char* seashell;
    const char* sienna;
    const char* quiksilver;
    const char* silver;
    const char* skyblue;
    const char* slateblue;
    const char* slategray;
    const char* slategrey;
    const char* snow;
    const char* springgreen;
    const char* steelblue;
    const char* sunflower;
    const char* tan;
    const char* teal;
    const char* thistle;
    const char* tomato;
    const char* turquoise;
    const char* violet;
    const char* wetasphalt;
    const char* wisteria;
    const char* wheat;
    const char* white;
    const char* whitesmoke;
    const char* yellow;
    const char* yellowgreen;
    const char* beekeeper;
    const char* spiced_nectarine;
    const char* pink_glamour;
    const char* june_bud;
    const char* coastal_breeze;
    const char* turbo;
    const char* quince_jelly;
    const char* carmine_pink;
    const char* pure_apple;
    const char* hint_of_ice_pack;
    const char* middle_blue;
    const char* heliotrope;
    const char* exodus_fruit;
    const char* deep_koamaru;
    const char* soaring_eagle;
    const char* greenland_green;
    const char* steel_pink;
    const char* blurple;
    const char* deep_cove;
    const char* wizard_grey;
    const char* highlighter_pink;
    const char* dark_periwinkle;
    const char* megaman;
    const char* fresh_turquoise;
    const char* minty_green;
    const char* sizzling_red;
    const char* free_speech_blue;
    const char* spiro_disco_ball;
    const char* jade_dust;
    const char* green_teal;
    const char* narenji_orange;
    const char* yriel_yellow;
    const char* sunset_orange;
    const char* hint_of_elusive_blue;
    const char* good_night;
    const char* chrome_yellow;
    const char* vibrant_yellow;
    const char* red_orange;
    const char* london_square;
    const char* black_pearl;
    const char* flat_flesh;
    const char* melon_melody;
    const char* livid;
    const char* spray;
    const char* paradise_green;
    const char* squash_blossom;
    const char* mandarin_red;
    const char* azraq_blue;
    const char* dupain;
    const char* aurora_green;
    const char* iceland_poppy;
    const char* tomato_red;
    const char* good_samaritan;
    const char* waterfall;
    const char* carrot_orange;
    const char* jalapeno_red;
    const char* dark_sapphire;
    const char* forest_blues;
    const char* reef_encounter;
    const char* jigglypuff;
    const char* casandora_yellow;
    const char* pastel_red;
    const char* megaman;
    const char* wild_caribbean_green;
    const char* lotus_pink;
    const char* double_dragon_skin;
    const char* amour;
    const char* cyanite;
    const char* dark_mountain_meadow;
    const char* jade_dust;
    const char* joust_blue;
    const char* nasu_purple;
    const char* light_blue_ballerina;
    const char* fuel_town;
    const char* aqua_velvet;
    const char* bleu_de_france;
    const char* bluebell;
    const char* storm_petrel;
    const char* imperial_primer;
    const char* orchid_orange;
    const char* spiro_disco_ball;
    const char* honey_glow;
    const char* sweet_garden;
    const char* falling_star;
    const char* rich_gardenia;
    const char* clear_chill;
    const char* sarawak_white_pepper;
    const char* keppel;
    const char* ships_officer;
    const char* fiery_fuchsia;
    const char* bluebell;
    const char* georgia_peach;
    const char* oasis_stream;
    const char* bright_ube;
    const char* magenta_purple;
    const char* ending_navy_blue;
    const char* sasquatch_socks;
    const char* pine_glade;
    const char* highlighter_lavender;
    const char* bright_lilac;
    const char* pretty_please;
    const char* light_red;
    const char* mandarin_sorbet;
    const char* unmellow_yellow;
    const char* light_purple;
    const char* young_salmon;
    const char* red_orange;
    const char* radiant_yellow;
    const char* dorn_yellow;
    const char* wintergreen;
    const char* electric_blue;
    const char* neon_blue;
    const char* light_slate_blue;
    const char* shadowed_steel;
    const char* weird_green;
    const char* hammam_blue;
    const char* spiro_disco_ball;
    const char* light_indigo;
    const char* baltic_sea;
    const char* sunflower;
    const char* energos;
    const char* blue_martina;
    const char* lavender_rose;
    const char* bara_red;
    const char* radiant_yellow;
    const char* android_green;
    const char* mediterranean_sea;
    const char* lavender_tea;
    const char* very_berry;
    const char* puffins_bill;
    const char* pixelated_grass;
    const char* merchant_marine_blue;
    const char* forgotten_purple;
    const char* hollyhock;
    const char* red_pigment;
    const char* turkish_aqua;
    const char* under_the_sea;
    const char* circumorbital_ring;
    const char* magenta_purple;
    const char* protoss_pylon;
    const char* periwinkle;
    const char* rise_n_shine;
    const char* download_progress;
    const char* seabrook;
    const char* vanadyl_blue;
    const char* matt_purple;
    const char* nanohanacha_gold;
    const char* skirret_green;
    const char* naval;
    const char* nasturcian_flower;
    const char* lynx_white;
    const char* blueberry_soda;
    const char* mazarine_blue;
    const char* blue_nights;
    const char* harley_davidson_orange;
    const char* hint_of_pensive;
    const char* chain_gang_grey;
    const char* pico_void;
    const char* electromagnetic;
};

const struct Colors colors = {
    .aliceblue = "#f0f8ff",
    .alizarin = "#e74c3c",
    .amethyst = "#9b59b6",
    .antiquewhite = "#faebd7",
    .aqua = "#00ffff",
    .aquamarine = "#7fffd4",
    .asbestos = "#7f8c8d",
    .azure = "#f0ffff",
    .beige = "#f5f5dc",
    .belizehole = "#2980b9",
    .bisque = "#ffe4c4",
    .black = "#000000",
    .blanchedalmond = "#ffebcd",
    .blue = "#0000ff",
    .blueviolet = "#8a2be2",
    .brown = "#a52a2a",
    .buff = "#f0dc82",
    .burlywood = "#deb887",
    .cadetblue = "#5f9ea0",
    .carrot = "#e67e22",
    .chartreuse = "#7fff00",
    .chocolate = "#d2691e",
    .clouds = "#ecf0f1",
    .concrete = "#95a5a6",
    .coral = "#ff7f50",
    .cornflowerblue = "#6495ed",
    .cornsilk = "#fff8dc",
    .crimson = "#dc143c",
    .cyan = "#00ffff",
    .darkblue = "#00008b",
    .darkbrown = "#5c4033",
    .darkbuff = "#976638",
    .darkcyan = "#008b8b",
    .darkgold = "#eebc1d",
    .darkgoldenrod = "#b8860b",
    .darkgray = "#404040",
    .darkgreen = "#006400",
    .darkgrey = "#a9a9a9",
    .darkivory = "#f2e58f",
    .darkkhaki = "#bdb76b",
    .darkmagenta = "#8b008b",
    .darkmustard = "#7c7c40",
    .darkolivegreen = "#556b2f",
    .darkorange = "#ff8c00",
    .darkorchid = "#9932cc",
    .darkpink = "#e75480",
    .darkred = "#8b0000",
    .darksalmon = "#e9967a",
    .darksilver = "#afafaf",
    .darkseagreen = "#8fbc8f",
    .darkslateblue = "#483d8b",
    .darkslategray = "#2f4f4f",
    .darkslategrey = "#2f4f4f",
    .darkturquoise = "#00ced1",
    .darkviolet = "#9400d3",
    .darkyellow = "#ffcc00",
    .deeppink = "#ff1493",
    .deepskyblue = "#00bfff",
    .dimgray = "#696969",
    .dimgrey = "#696969",
    .dodgerblue = "#1e90ff",
    .emerald = "#2ecc71",
    .firebrick = "#b22222",
    .floralwhite = "#fffaf0",
    .forestgreen = "#228b22",
    .fuchsia = "#ff00ff",
    .gainsboro = "#dcdcdc",
    .ghostwhite = "#f8f8ff",
    .gold = "#ffd700",
    .goldenrod = "#daa520",
    .gray = "#808080",
    .green = "#008000",
    .greensea = "#16a085",
    .greenyellow = "#adff2f",
    .grey = "#808080",
    .honeydew = "#f0fff0",
    .hotpink = "#ff69b4",
    .indianred = "#cd5c5c",
    .indigo = "#4b0082",
    .ivory = "#fffff0",
    .khaki = "#f0e68c",
    .lavender = "#e6e6fa",
    .lavenderblush = "#fff0f5",
    .lawngreen = "#7cfc00",
    .lemonchiffon = "#fffacd",
    .lightblack = "#808080",
    .lightblue = "#add8e6",
    .lightbrown = "#9966ff",
    .lightbuff = "#ecd9b0",
    .lightcoral = "#f08080",
    .lightcyan = "#e0ffff",
    .lightgold = "#f1e5ac",
    .lightgoldenrod = "#ffec8b",
    .lightgoldenrodyellow = "#fafad2",
    .lightgray = "#d3d3d3",
    .lightgreen = "#90ee90",
    .lightgrey = "#d3d3d3",
    .lightivory = "#fff8c9",
    .lightmagenta = "#ff77ff",
    .lightmustard = "#eedd62",
    .lightorange = "#d9a465",
    .lightpink = "#ffb6c1",
    .lightred = "#ff3333",
    .lightsalmon = "#ffa07a",
    .lightseagreen = "#20b2aa",
    .lightsilver = "#e1e1e1",
    .lightskyblue = "#87cefa",
    .lightslategray = "#778899",
    .lightslategrey = "#778899",
    .lightsteelblue = "#b0c4de",
    .lightturquoise = "#afe4de",
    .lightviolet = "#7a5299",
    .lightyellow = "#ffffe0",
    .lime = "#00ff00",
    .limegreen = "#32cd32",
    .linen = "#faf0e6",
    .magenta = "#ff00ff",
    .maroon = "#800000",
    .mediumaquamarine = "#66cdaa",
    .mediumblue = "#0000cd",
    .mediumorchid = "#ba55d3",
    .mediumpurple = "#9370db",
    .mediumseagreen = "#3cb371",
    .mediumslateblue = "#7b68ee",
    .mediumspringgreen = "#00fa9a",
    .mediumturquoise = "#48d1cc",
    .mediumvioletred = "#c71585",
    .midnightblue = "#191970",
    .midnightblack = "#2c3e50",
    .mintcream = "#f5fffa",
    .mistyrose = "#ffe4e1",
    .moccasin = "#ffe4b5",
    .mustard = "#ffdb58",
    .nephritis = "#27ae60",
    .navajowhite = "#ffdead",
    .navy = "#000080",
    .oldlace = "#fdf5e6",
    .olive = "#808000",
    .olivedrab = "#6b8e23",
    .orange = "#ffa500",
    .orangered = "#ff4500",
    .orchid = "#da70d6",
    .palegoldenrod = "#eee8aa",
    .palegreen = "#98fb98",
    .paleturquoise = "#afeeee",
    .palevioletred = "#db7093",
    .papayawhip = "#ffefd5",
    .peachpuff = "#ffdab9",
    .peterriver = "#3498db",
    .peru = "#cd853f",
    .pink = "#ffc0cb",
    .plum = "#dda0dd",
    .pomegranate = "#c0392b",
    .powderblue = "#b0e0e6",
    .purple = "#800080",
    .pumpkin = "#d35400",
    .rebeccapurple = "#663399",
    .red = "#ff0000",
    .rosybrown = "#bc8f8f",
    .royalblue = "#4169e1",
    .saddlebrown = "#8b4513",
    .salmon = "#fa8072",
    .sandybrown = "#f4a460",
    .seagreen = "#2e8b57",
    .seashell = "#fff5ee",
    .sienna = "#a0522d",
    .quiksilver = "#bdc3c7",
    .silver = "#c0c0c0",
    .skyblue = "#87ceeb",
    .slateblue = "#6a5acd",
    .slategray = "#708090",
    .slategrey = "#708090",
    .snow = "#fffafa",
    .springgreen = "#00ff7f",
    .steelblue = "#4682b4",
    .sunflower = "#f1c40f",
    .tan = "#d2b48c",
    .teal = "#008080",
    .thistle = "#d8bfd8",
    .tomato = "#ff6347",
    .turquoise = "#40e0d0",
    .violet = "#ee82ee",
    .wetasphalt = "#34495e",
    .wisteria = "#8e44ad",
    .wheat = "#f5deb3",
    .white = "#ffffff",
    .whitesmoke = "#f5f5f5",
    .yellow = "#ffff00",
    .yellowgreen = "#9acd32",
    .beekeeper = "#f6e58d",
    .spiced_nectarine = "#ffbe76",
    .pink_glamour = "#ff7979",
    .june_bud = "#badc58",
    .coastal_breeze = "#dff9fb",
    .turbo = "#f9ca24",
    .quince_jelly = "#f0932b",
    .carmine_pink = "#eb4d4b",
    .pure_apple = "#6ab04c",
    .hint_of_ice_pack = "#c7ecee",
    .middle_blue = "#7ed6df",
    .heliotrope = "#e056fd",
    .exodus_fruit = "#686de0",
    .deep_koamaru = "#30336b",
    .soaring_eagle = "#95afc0",
    .greenland_green = "#22a6b3",
    .steel_pink = "#be2edd",
    .blurple = "#4834d4",
    .deep_cove = "#130f40",
    .wizard_grey = "#535c68",
    .highlighter_pink = "#ef5777",
    .dark_periwinkle = "#575fcf",
    .megaman = "#4bcffa",
    .fresh_turquoise = "#34e7e4",
    .minty_green = "#0be881",
    .sizzling_red = "#f53b57",
    .free_speech_blue = "#3c40c6",
    .spiro_disco_ball = "#0fbcf9",
    .jade_dust = "#00d8d6",
    .green_teal = "#05c46b",
    .narenji_orange = "#ffc048",
    .yriel_yellow = "#ffdd59",
    .sunset_orange = "#ff5e57",
    .hint_of_elusive_blue = "#d2dae2",
    .good_night = "#485460",
    .chrome_yellow = "#ffa801",
    .vibrant_yellow = "#ffd32a",
    .red_orange = "#ff3f34",
    .london_square = "#808e9b",
    .black_pearl = "#1e272e",
    .flat_flesh = "#fad390",
    .melon_melody = "#f8c291",
    .livid = "#6a89cc",
    .spray = "#82ccdd",
    .paradise_green = "#b8e994",
    .squash_blossom = "#f6b93b",
    .mandarin_red = "#e55039",
    .azraq_blue = "#4a69bd",
    .dupain = "#60a3bc",
    .aurora_green = "#78e08f",
    .iceland_poppy = "#fa983a",
    .tomato_red = "#eb2f06",
    .good_samaritan = "#3c6382",
    .waterfall = "#38ada9",
    .carrot_orange = "#e58e26",
    .jalapeno_red = "#b71540",
    .dark_sapphire = "#0c2461",
    .forest_blues = "#0a3d62",
    .reef_encounter = "#079992",
    .jigglypuff = "#ff9ff3",
    .casandora_yellow = "#feca57",
    .pastel_red = "#ff6b6b",
    .megaman = "#48dbfb",
    .wild_caribbean_green = "#1dd1a1",
    .lotus_pink = "#f368e0",
    .double_dragon_skin = "#ff9f43",
    .amour = "#ee5253",
    .cyanite = "#0abde3",
    .dark_mountain_meadow = "#10ac84",
    .jade_dust = "#00d2d3",
    .joust_blue = "#54a0ff",
    .nasu_purple = "#5f27cd",
    .light_blue_ballerina = "#c8d6e5",
    .fuel_town = "#576574",
    .aqua_velvet = "#01a3a4",
    .bleu_de_france = "#2e86de",
    .bluebell = "#341f97",
    .storm_petrel = "#8395a7",
    .imperial_primer = "#222f3e",
    .orchid_orange = "#fea47f",
    .spiro_disco_ball = "#25ccf7",
    .honey_glow = "#eab543",
    .sweet_garden = "#55e6c1",
    .falling_star = "#cad3c8",
    .rich_gardenia = "#f97f51",
    .clear_chill = "#1b9cfc",
    .sarawak_white_pepper = "#f8efba",
    .keppel = "#58b19f",
    .ships_officer = "#2c3a47",
    .fiery_fuchsia = "#b33771",
    .bluebell = "#3b3b98",
    .georgia_peach = "#fd7272",
    .oasis_stream = "#9aecdb",
    .bright_ube = "#d6a2e8",
    .magenta_purple = "#6d214f",
    .ending_navy_blue = "#182c61",
    .sasquatch_socks = "#fc427b",
    .pine_glade = "#bdc581",
    .highlighter_lavender = "#82589f",
    .bright_lilac = "#cd84f1",
    .pretty_please = "#ffcccc",
    .light_red = "#ff4d4d",
    .mandarin_sorbet = "#ffaf40",
    .unmellow_yellow = "#fffa65",
    .light_purple = "#c56cf0",
    .young_salmon = "#ffb8b8",
    .red_orange = "#ff3838",
    .radiant_yellow = "#ff9f1a",
    .dorn_yellow = "#fff200",
    .wintergreen = "#32ff7e",
    .electric_blue = "#7efff5",
    .neon_blue = "#18dcff",
    .light_slate_blue = "#7d5fff",
    .shadowed_steel = "#4b4b4b",
    .weird_green = "#3ae374",
    .hammam_blue = "#67e6dc",
    .spiro_disco_ball = "#17c0eb",
    .light_indigo = "#7158e2",
    .baltic_sea = "#3d3d3d",
    .sunflower = "#ffc312",
    .energos = "#c4e538",
    .blue_martina = "#12cbc4",
    .lavender_rose = "#fda7df",
    .bara_red = "#ed4c67",
    .radiant_yellow = "#f79f1f",
    .android_green = "#a3cb38",
    .mediterranean_sea = "#1289a7",
    .lavender_tea = "#d980fa",
    .very_berry = "#b53471",
    .puffins_bill = "#ee5a24",
    .pixelated_grass = "#009432",
    .merchant_marine_blue = "#0652dd",
    .forgotten_purple = "#9980fa",
    .hollyhock = "#833471",
    .red_pigment = "#ea2027",
    .turkish_aqua = "#006266",
    .under_the_sea = "#1b1464",
    .circumorbital_ring = "#5758bb",
    .magenta_purple = "#6f1e51",
    .protoss_pylon = "#00a8ff",
    .periwinkle = "#9c88ff",
    .rise_n_shine = "#fbc531",
    .download_progress = "#4cd137",
    .seabrook = "#487eb0",
    .vanadyl_blue = "#0097e6",
    .matt_purple = "#8c7ae6",
    .nanohanacha_gold = "#e1b12c",
    .skirret_green = "#44bd32",
    .naval = "#40739e",
    .nasturcian_flower = "#e84118",
    .lynx_white = "#f5f6fa",
    .blueberry_soda = "#7f8fa6",
    .mazarine_blue = "#273c75",
    .blue_nights = "#353b48",
    .harley_davidson_orange = "#c23616",
    .hint_of_pensive = "#dcdde1",
    .chain_gang_grey = "#718093",
    .pico_void = "#192a56",
    .electromagnetic = "#2f3640",
};
